= Project Order

==== Lorenz Gruber, Simon Ittensammer, Simon Zweimüller

{sp} +

== Initial situation

* There are already surveillance systems, which stream their videos to an interface +
* People need to take their medicine while watching television

== Problems

* These systems leave little room for personalization
* It is quite tricky to stream different videos from different cameras to the same            interface
* People often forget about important things, like taking their medicine, while watching      television

== Tasks
* Create an interface, which lets the user easily switch between different videos
* Let the user add additional videos to the interface
* Let the user create personalized messages, which are displayed in the video
* Let the user schedule a personalized message, which is going to be shown on TV

== Usefulness
* Users need less time to configure their surveillance systems
* People are reminded about important things, if it is taking medidicine it could even be     life saving
