= CAMeleon
Lorenz Gruber, Simon Ittensammer, Simon Zweimüller
1.0.1, 2020-03-29

== Description

This application allows you to manage your surveillance cameras. +
You can personalize the surveillance videos with images, text and other objects. +
Whenever movement is detected you will be notified and you will also be able to see a short clip of the movement action.

== Overview

https://simonittensammer.github.io/cameleon/[]

== State

=== Current

With the current state of the project, the user can view streams on the webpage. +
He is also able to add videostreams on the webpage. +
These streams are persisted in the local mongodb database, which means that they will also be shown after you reload the page. +
After the streams where added to the database, the user is still able to change the name, description and url of his streams, by using the edit button on the client. +
The user can also  lay texts, images and other objects over his streams.

=== In Progress

We are currently working on a feature, which allows the user to receive notifications via Telegram. +
We are also working on recording short videoclips from the stream footage.

=== Next Steps

The next feature will be motion detection. +
