= CAMeleon
Lorenz Gruber, Simon Ittensammer, Simon Zweimüller
1.0.3, 2020-11-17

=== Description

CAMeleon is a easy-to-use surveillance system for ip-cameras, complete with motion detection, customizable overlays and automatic notifications. It lets you connect devices and video streams via their url and allowes you to view and manage them on a neat user interface.

=== Runing the application

Start up the start-in-docker.sh
[source, bash]
----
./start-in-docker.sh
----

Then you can reach the application at localhost:4200

==== Windows with Docker Toolbox

If you run Docker on your Windows with the Docker Toolbox you have to change the SERVER_URL in the https://github.com/simonittensammer/cameleon/blob/master/cameleon-frontend/src/app/services/cam.service.ts[cam.service.ts] file to your virtual IP.

The application will also be reached under the virtual IP and not under localhost

=== Setting up your first IP-Cam

The easiest way to use Cameleon ist with the IP Webcam App for your Smartphone. This turns your Smartphone Camera into an IP-Cam. 
After starting the videostream you can access it with an URL similar to this one:

[source]
----
http://10.0.0.5:8080/video
----

IP Webcam App: https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en_US&gl=US
