= Technologien
simon ittensammer
1.1.0, 2020-09-29: Used Technologies in "Cameleon"
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

== Backend

=== Server
* *NodeJS:* Hostet die Website und ist für alle unten stehenden Backend-Funktionen verantwortlich.

=== Aufnehmen von Bildern/Videos & Bewegungserkennung
* *OpenCV 4 NodeJS:* Ermöglicht es Frames aus einem Videostream abzugreifen um diese später zu speichern, zu verschicken oder weiterzuverarbeiten. Auch verwenden wir OpenCV um verschiedene Frames zu vergleichen und so Bewegung erkennen können.

=== Overlay
* *Text2Png*: Erzeugt aus einem Eingabe-String ein PNG-Bild.
* *Jimp:* Mithilfe von Jimp werden die Overlay-Objekte, also Bilder oder Texte, in einen Frame eingearbeitet.

=== Benachrichtigung
* *Telegram-Bot API:* Diese API ermöglicht es automatische Nachrichten per Telegram an den User zu senden.

=== WebCam als IP-Kamera
* *ffmpeg:* Ermöglicht es eine normale WebCam als IP-Camera zu verwenden.

== Datenbank

* *MongoDB:* Ist für die Speicherung aller Daten zuständig. Diese sind z.B. Overlay-Objekte oder Kamerainfos.

== Frontend

* *Reines JavaScript:* Mithilfe von JS werden Clientseitig alle Funktionen umgesetzt. Diese sind z.B. das Verschieben von Overlay-Elementen.

== Kommunikation

* *Websockets:* Ermöglicht eine bidirektionale Kommunikation zwischen Client und Server. So werden z.B. neue Kameras und Overlays hinzugefügt. Auch können durch WebSockets Push-Notifications am Client angezeigt werden.
