[plantuml, component-diagram, png, align-center]
----
@startuml


skinparam handwritten true
skinparam ArrowColor #19171c
skinparam ArrowFontColor #8189c6
skinparam ComponentFontColor white
skinparam DatabaseFontColor white
skinparam PackageFontColor white
skinparam shadowing false

skinparam node {
  BackgroundColor #52577b
  BorderColor #4b367c
}

skinparam package {
  BackgroundColor #707299
  BorderColor #4b367c
}

skinparam component {
  BackgroundColor #8189c6
  BorderColor #4b367c
}

node {
    [Camera]
}

node {
    package "Docker Backend" {
        [Quarkus Server]
    }

    package "Docker Frontend" {
        [Angular Application]
    }

    package "Docker DB" {
        database "postgresql" {
            [Cameleon DB]
        }
    }
}

node {
    package "Client" {
        [Browser]
    }
}

[Camera] -> [Quarkus Server] : HTTP
[Camera] -> [Angular Application] : HTTP
[Angular Application] --> [Quarkus Server] : REST
[Quarkus Server] --> [Cameleon DB]
[Browser] -> [Angular Application]

@enduml
----