[plantuml, component-diagram, png, align-center]
----
@startuml

!include style.puml

node {
    [Camera]
}

node {
    package "Docker Backend" {
        [Quarkus Server]
    }

    package "Docker Frontend" {
        [Angular Application]
    }

    package "Docker DB" {
        database "postgresql" {
            [Cameleon DB]
        }
    }
}

node {
    package "Client" {
        [Browser]
        [Telegram]
    }
}

[Camera] -> [Quarkus Server] : HTTP
[Camera] -> [Angular Application] : HTTP
[Angular Application] --> [Quarkus Server] : REST
[Quarkus Server] --> [Cameleon DB]
[Browser] -> [Angular Application]
[Quarkus Server] -> [Telegram]
[Browser] -[hidden]-> [Telegram]

@enduml
----

